=== liversohn/dr8parser/data/dr8_CRo_v100_RC2.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Report">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="1">
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="Record"> </xs:element>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="Simulcasting">
					<xs:complexType>
						<xs:attribute name="from" type="xs:dateTime" use="required"/>
						<xs:attribute name="to" type="xs:dateTime" use="required"/>
						<xs:attribute name="station" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="dateFrom" type="xs:date" use="required"/>
			<xs:attribute name="dateTo" type="xs:date" use="required"/>
			<xs:attribute name="station" type="xs:string" use="required"/>
			<xs:attribute name="usageType" type="ReportUsageType" use="required"/>
			<xs:attribute name="filename" type="xs:string" use="required"/>
			<xs:attribute name="sender" type="xs:string"/>
			<xs:attribute name="encoding" type="xs:string"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="StringNotNull">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PositiveIntType">
		<xs:restriction base="xs:integer">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NonNegativeIntType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISRCType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="YearType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9][0-9][0-9][0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReportUsageType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="commercial"/>
			<xs:enumeration value="jingle"/>
			<xs:enumeration value="broadcast"/>
			<xs:enumeration value="internet"/>
			<xs:enumeration value="mix"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ModifierEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="A"/>
			<xs:enumeration value="B"/>
			<xs:enumeration value="C"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="GenreEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="classical"/>
			<xs:enumeration value="spoken word"/>
			<xs:enumeration value="pop"/>
			<xs:enumeration value="composed"/>
			<xs:enumeration value="commercial"/>
			<xs:enumeration value="jingle"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RecordUsageType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="commercial"/>
			<xs:enumeration value="jingle"/>
			<xs:enumeration value="broadcast"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="grossFeeType">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits fixed="true" value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RoleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="performer"/>
			<xs:enumeration value="arranger"/>
			<xs:enumeration value="composer"/>
			<xs:enumeration value="music director"/>
			<xs:enumeration value="producer"/>
			<xs:enumeration value="remixer"/>
			<xs:enumeration value="scriptwriter"/>
			<xs:enumeration value="sound engineer"/>
			<xs:enumeration value="subscriptwriter"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PerformanceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="main"/>
			<xs:enumeration value="supporting"/>
			<xs:enumeration value="soloist"/>
			<xs:enumeration value="conductor"/>
			<xs:enumeration value="chorus master"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OriginEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="self"/>
			<xs:enumeration value="live broadcasting"/>
			<xs:enumeration value="live stream"/>
			<xs:enumeration value="recorded stream"/>
			<xs:enumeration value="free usage"/>
			<xs:enumeration value="report"/>
			<xs:enumeration value="free of charge"/>
			<xs:enumeration value="commerce"/>
			<xs:enumeration value="commercial"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Record">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Participants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Participant" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" type="StringNotNull" use="required"/>
									<xs:attribute name="role" type="RoleType" use="required"/>
									<xs:attribute name="IPDN" type="xs:string"/>
									<xs:attribute name="performance" type="PerformanceType"/>
									<xs:attribute name="grossFee" type="grossFeeType"/>
									<xs:attribute name="modifier" type="ModifierEnum"/>
									<xs:attribute name="IPI" type="xs:string"/>
									<xs:attribute name="birthDate" type="xs:date" use="required"/>
									<xs:anyAttribute processContents="lax"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="Record"/>
			</xs:sequence>
			<xs:attribute name="title" type="StringNotNull" use="required"/>
			<xs:attribute name="spins" type="PositiveIntType" use="required"/>
			<xs:attribute name="ISRC" type="ISRCType" use="optional"/>
			<xs:attribute name="year" type="YearType" use="optional"/>
			<xs:attribute name="producer" type="xs:string" use="optional"/>
			<xs:attribute name="label" type="xs:string" use="optional"/>
			<xs:attribute name="recordNo" type="xs:string" use="optional"/>
			<xs:attribute name="serialNumber" type="xs:string" use="optional"/>
			<xs:attribute name="isPremiere" type="xs:boolean"/>
			<xs:attribute name="usage" type="RecordUsageType" use="optional"/>
			<xs:attribute name="ISWC" type="xs:string" use="optional"/>
			<xs:attribute name="AKA" type="xs:string"/>
			<xs:attribute name="genre" type="GenreEnum"/>
			<xs:attribute name="broadcastedFrom" type="xs:dateTime" use="optional"/>
			<xs:attribute name="broadcastedTo" type="xs:dateTime" use="optional"/>
			<xs:attribute name="runtime" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="origin" type="OriginEnum"/>
			<xs:attribute name="alternativeTitle" type="StringNotNull" use="optional"/>
			<xs:attribute name="recordedFootage" type="xs:nonNegativeInteger" use="required"/>
			<xs:anyAttribute processContents="lax"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== liversohn/dr8parser/data/test-small.xml
<?xml version="1.0" encoding="UTF-8"?>
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/media/richard/KINGSTON/dr8_CRo_v100_RC2.xsd" dateFrom="2020-06-07" dateTo="2019-09-15Z" station="KGc4hNsxivpDroB" usageType="broadcast" filename="T4QDMRnCkL.RPR4gEayZbHgkfa"
     sender="RL2c1_" encoding="aob0TRIjbDrp.4kGN5O8">
    <Record title="ED" spins="404611556" ISRC="UHZP8JAR4H77" year="4427" producer="YntfLSLx" label="crRjLQU-" recordNo="ZbUltyhGRm9rbC7BnZEFiNM139KM"
         serialNumber="eJjjiRb-o_5nbh" isPremiere="1" usage="jingle" ISWC="d" AKA="Y" genre="pop" broadcastedFrom="2019-09-03T11:21:16"
         broadcastedTo="2020-06-26T11:21:16" runtime="732033996" origin="free usage" alternativeTitle="fbzOvJZ"
         recordedFootage="1617320623">
        <Participants>
            <Participant name="KfvFXWhf" role="scriptwriter" IPDN="KISIviZ-en1oWb" performance="soloist" grossFee="-1497279826.34"
                 modifier="B" IPI="SR6hVDHnmUXvH5k" birthDate="2019-09-29Z"/>
            <Participant name="jRk3RD" role="subscriptwriter" IPDN="cEoNLhfM" performance="chorus master" grossFee="1966561299.70"
                 modifier="A" IPI="N67" birthDate="2019-07-28Z"/>
            <Participant name="CYkIqknDt8i_ShxmEQLN4r6" role="remixer" IPDN="pRJRNV4iEQ" performance="chorus master" grossFee="2033955477.80"
                 modifier="C" IPI="bDYh-0tnQr6K4cjaKACluNAP" birthDate="2020-02-05"/>
            <Participant name="GHnko7xxW" role="performer" IPDN="Lf" performance="conductor" grossFee="-1863095323.18" modifier="B"
                 IPI="i0uiL4SkRp" birthDate="2018-12-03"/>
            <Participant name="oy5PQtnf6GzaJC54i" role="sound engineer" IPDN="wTY9531ZAf.EYH7tIQc6K" performance="chorus master"
                 grossFee="-904582624.20" modifier="A" IPI="oQLEP8qM9.lb_" birthDate="2019-05-27Z"/>
        </Participants>
    </Record>
    <Record title="ntP8whEvW4U_p__6SHMkPRE7tKJ" spins="640746775" ISRC="SMR5MHD10K49" year="6810" producer="kPNU7rAimdY9ZfaSkdlzQW0lQpEH"
         label="m.OmWC" recordNo="jNrBAPEoM" serialNumber="TkxlvG5" isPremiere="0" usage="broadcast"
         ISWC="qoD7OKwP1722K2OlgOrT3c4i6" AKA="mMF5sLt.Mer" genre="pop" broadcastedFrom="2018-07-30T11:21:16Z"
         broadcastedTo="2019-12-10T11:21:16" runtime="1983187026" origin="live stream" alternativeTitle="YeyaF49YN7ppna"
         recordedFootage="587383282">
        <Participants>
            <Participant name="mRj1DQ7cW5OWuVo" role="arranger" IPDN="TQ" performance="main" grossFee="381124579.76" modifier="C"
                 IPI="IDXo-L" birthDate="2018-07-06"/>
            <Participant name="d" role="scriptwriter" IPDN="iiA72" performance="supporting" grossFee="157972933.73" modifier="A"
                 IPI="Bwzy" birthDate="2018-09-11"/>
            <Participant name="DRCXS7bJ6mj6QGnEQTunIv7Ae5" role="producer" IPDN="HfdtIgTm" performance="chorus master" grossFee="-2076378010.64"
                 modifier="C" IPI="dUg2x7A6w6QmMzfZA4buaeh0" birthDate="2018-12-18Z"/>
            <Participant name="yxs3L3R" role="producer" IPDN="Q5LUixwEujAE" performance="main" grossFee="171246541.25" modifier="B"
                 IPI="ybgAo6j-jHPi7a3EUMFTp5BCxEQwYW" birthDate="2018-12-16Z"/>
            <Participant name="zpYRojT4X4G3RWnMQ.yJkbE" role="subscriptwriter" IPDN="tO22NKYnMaxsU2AjB-trVjI" performance="main"
                 grossFee="1137549854.49" modifier="B" IPI="A.9wcaAj" birthDate="2019-05-14Z"/>
        </Participants>
    </Record>
    <Record title="GhXgwGxJQXVbnv3cmpIIhUEW" spins="1961536928" ISRC="D8N2L0AE3GQD" year="2718" producer="TuVZjKo"
         label="iqM" recordNo="fLbpJWqubrb9q6a.T7hC2jJYqD" serialNumber="Gql" isPremiere="0" usage="jingle"
         ISWC="Jf0.XXUZn6Lw8Svs" AKA="vI5yBJLkhk" genre="classical" broadcastedFrom="2019-04-10T11:21:16Z"
         broadcastedTo="2020-05-17T11:21:16" runtime="1785127640" origin="free usage" alternativeTitle="fnRQXMZe5fgAVvM9wo_K4z4"
         recordedFootage="930906112">
        <Participants>
            <Participant name="iZTvQQcwe3damPu0pbQ2hFhX" role="arranger" IPDN="sjmDsxW" performance="main" grossFee="-71323070.96"
                 modifier="A" IPI="IHJQ84HBCkKAxjX1Cgw_zA6qUVNSNN" birthDate="2019-10-21Z"/>
            <Participant name="ICbf" role="producer" IPDN="c-ra5oKIIu_RCPcLa3aLtvL7J4" performance="supporting" grossFee="2096959224.57"
                 modifier="B" IPI="MVLwP7xdirKUOdBd" birthDate="2019-05-04Z"/>
            <Participant name="BaziQ" role="scriptwriter" IPDN="ma3OcXzalvmlfV5v8qwSMCZ" performance="chorus master" grossFee="1260214939.50"
                 modifier="A" IPI="OWN98OrWdlgV7O" birthDate="2019-08-03Z"/>
            <Participant name="iThOPhQBcV_81UX" role="subscriptwriter" IPDN="SMg1A5Ljr" performance="chorus master" grossFee="1633664720.27"
                 modifier="B" IPI="mB6IRiFehhvyd8K0pqH" birthDate="2019-02-16"/>
            <Participant name="j_jdk.Qncazc01M82h51" role="composer" IPDN="dyDYxWTxzrgeXDa6ET3SeB876y-5O3" performance="supporting"
                 grossFee="942306420.94" modifier="C" IPI="q5_ST2G6rsh820" birthDate="2019-05-16Z"/>
        </Participants>
    </Record>
    <Record title="I0QcHY7dvbb6D_aKB0V" spins="502027052" ISRC="0RPTU4B4V3KO" year="8503" producer="URj8JB3YNlAMjMAY"
         label="sBk7o2s" recordNo="vrXfH5uATPC" serialNumber="AmyL3ebcA" isPremiere="0" usage="commercial"
         ISWC="ISO" AKA="RhOe" genre="composed" broadcastedFrom="2020-02-06T11:21:16" broadcastedTo="2020-06-28T11:21:16"
         runtime="1970830705" origin="free of charge" alternativeTitle="k1" recordedFootage="2015220077">
        <Participants>
            <Participant name="qtgMvr0GT" role="composer" IPDN="wF_Ty5y3EW_rA6" performance="chorus master" grossFee="-1901135580.86"
                 modifier="B" IPI="sD6VBqSDgWFR58G" birthDate="2018-10-09Z"/>
            <Participant name="gG5-5vZDi" role="music director" IPDN="lMq7KINVB" performance="chorus master" grossFee="-700983760.81"
                 modifier="B" IPI="FpTu5kH9t9kM-PAtgfmAN" birthDate="2019-04-15"/>
            <Participant name="gVIzX9JgAkG_TeEO7guGcF2" role="music director" IPDN="KZCn3dy4hB3sBEqmcCJURvIyl" performance="soloist"
                 grossFee="-1630725768.15" modifier="C" IPI="v2WDMgrkpNv9_z4Rw-0BSTg" birthDate="2020-04-13Z"/>
            <Participant name="dG" role="remixer" IPDN="Bqd2c7cldL1sE5mRSJQHGmF7" performance="conductor" grossFee="-2102106519.62"
                 modifier="C" IPI="_zr8QOC60y6" birthDate="2018-07-06Z"/>
            <Participant name="Hd3o3hdL4e4Y" role="sound engineer" IPDN="C-BGxBLGyeN.wlxQwS94nB9ht22r" performance="main" grossFee="469754820.34"
                 modifier="B" IPI="xouf1dgrZUXMI" birthDate="2018-10-19Z"/>
        </Participants>
    </Record>
    <Record title="ldff-c0Ogueb5hePy2RGbOjt" spins="418701817" ISRC="0CU2PSO9G4F2" year="5532" producer="pOGi0pnbe7y2"
         label="DIEX" recordNo="tsAC_LknIdqvZP1oxlTvZHy" serialNumber="NzRVGfjTpdu9Oa30Wn9" isPremiere="0"
         usage="commercial" ISWC="UJnur_4oM" AKA="fqoyV.r" genre="jingle" broadcastedFrom="2019-04-19T11:21:16"
         broadcastedTo="2018-11-06T11:21:16" runtime="857072318" origin="live broadcasting" alternativeTitle="cxjFDPnsfD95j"
         recordedFootage="1741133870">
        <Participants>
            <Participant name="ILTVTYXsYGw5" role="remixer" IPDN="lrM5R-DeCvQA08f4Yeu" performance="conductor" grossFee="-1049192414.01"
                 modifier="C" IPI="DlRV9XKeHqmt" birthDate="2018-07-19Z"/>
            <Participant name="QH" role="producer" IPDN="z22OY53L_Hg8jXSa5AF7r-D8kKSlTQ" performance="conductor" grossFee="2069067433.09"
                 modifier="A" IPI="IuLatIs" birthDate="2020-03-18"/>
            <Participant name="HdjxO17hgmzr_SjSY" role="sound engineer" IPDN="N" performance="chorus master" grossFee="-1923744973.31"
                 modifier="A" IPI="ap_rA68DNgzv" birthDate="2020-06-12"/>
            <Participant name="yifoVbgU0l1enqcDHGw" role="composer" IPDN="leKrn5buHdGx.sQoFv" performance="main" grossFee="-801945765.94"
                 modifier="C" IPI="hy3cmG" birthDate="2019-05-17Z"/>
            <Participant name="Q" role="music director" IPDN="uPyx" performance="soloist" grossFee="422343486.63" modifier="A"
                 IPI="f8DbS0" birthDate="2019-11-02Z"/>
        </Participants>
    </Record>
    <Simulcasting from="2019-01-07T11:21:16" to="2019-12-02T11:21:16Z" station="ZLqv1EyllE0fVcUdnUsF_"/>
    <Simulcasting from="2020-04-07T11:21:16Z" to="2019-04-27T11:21:16" station="Ro0uuZrPs"/>
    <Simulcasting from="2020-04-17T11:21:16Z" to="2019-05-13T11:21:16Z" station="Ver"/>
    <Simulcasting from="2019-01-05T11:21:16Z" to="2018-11-22T11:21:16" station="VCXzQBm"/>
    <Simulcasting from="2018-07-10T11:21:16" to="2018-11-25T11:21:16" station="t-1hAIOP_R-Kljrx.OFWhhm"/>
    <Record title="E8YemL" spins="639018769" ISRC="4791ZQV5555U" year="4290" producer="TUJIiNGF" label="Vc" recordNo="B970N.yZWWQ5rTgfv8D"
         serialNumber="msco" isPremiere="true" usage="jingle" ISWC="pqyHHpnu2heIaN" AKA="vuJBW" genre="jingle"
         broadcastedFrom="2019-07-07T11:21:16" broadcastedTo="2018-09-08T11:21:16" runtime="488307726"
         origin="commercial" alternativeTitle="Hxu90r8jgQVMXsCv-p8rBIXhy8" recordedFootage="1296752356">
        <Participants>
            <Participant name="VR4EWTJzce9fn17sMmxyF" role="producer" IPDN="dQ99F1TXVqXyR9k7eIVvEp0B2" performance="conductor"
                 grossFee="1138484388.05" modifier="B" IPI="dEeK.dqco5LfLM" birthDate="2019-09-08Z"/>
            <Participant name="RJO6-tTKuAwKdmVzixoeVf" role="arranger" IPDN="zVOnl" performance="chorus master" grossFee="-1893785772.29"
                 modifier="A" IPI="kHVZWjRX4w88EelO2EYD8bRiuVL" birthDate="2019-08-14Z"/>
